name: Setup Infracost
description: Setup infracost.

inputs:
  api-key:
    description: Infracost api key
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
      shell: bash
    - run: |
        mkdir -p .config/infracost
        echo -e "version: \"0.1\"\napi_key: ${{ inputs.api-key }}\npricing_api_endpoint: https://pricing.api.infracost.io" > .config/infracost/credentials.yml
      shell: bash
