name: Setup Go
description: Setup the go tools.

inputs:
  go-version:
    description: Go version to install
    required: false
    default: 1.17
  mage-version:
    description: Mage version to install
    required: false
    default: 1.11.0

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
    - uses: actions/cache@v2
      id: cache-mage
      with:
        path: ~/.local/bin/mage
        key: ${{ runner.os }}-mage-${{ hashFiles('~/.local/bin/mage') }}
    - run: |
        curl -sSL https://github.com/magefile/mage/releases/download/v${{ inputs.mage-version }}/mage_${{ inputs.mage-version }}_Linux-64bit.tar.gz | tar -xzf- mage
        chmod +x mage
        mkdir -p ~/.local/bin
        mv mage ~/.local/bin
      if: steps.cache-mage.outputs.cache-hit != 'true'
      shell: bash
    - uses: actions/cache@v2
      id: cache-vendor
      with:
        path: vendor/
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
    - run: |
        go mod vendor
      if: steps.cache-vendor.outputs.cache-hit != 'true'