name: Setup Terraform
description: Setup the terraform tools.

inputs:
  tfsec-version:
    description: tfsec version to install
    required: false
    default: 0.63.1

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      id: cache-tfenv
      with:
        path: |
          ~/.tfenv
          ~/.local/bin
        key: ${{ runner.os }}-tfenv-${{ hashFiles('.terraform-version') }}
    - uses: actions/cache@v2
      id: cache-tfsec
      with:
        path: |
          ~/.local/bin/tfsec
        key: ${{ runner.os }}-tfsec-${{ hashFiles('~/.local/bin/tfsec') }}
    - run: |
        git clone https://github.com/tfutils/tfenv.git ~/.tfenv
        ln -s ~/.tfenv/bin/* ~/.local/bin
      if: steps.cache-tfenv.outputs.cache-hit != 'true'
      shell: bash
    - run: |
        curl -sSL https://github.com/aquasecurity/tfsec/releases/download/v${{ inputs.tfsec-version }}/tfsec-linux-amd64 > ~/.local/bin/tfsec
        chmod +x ~/.local/bin/tfsec
      if: steps.cache-tfsec.outputs.cache-hit != 'true'
      shell: bash
    - run: |
        tfenv install
      shell: bash
