name: Workflow - On All Branches

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/setup-terraform
      - run: |
          mage -v lint

  test:
    runs-on: ubuntu-20.04
    name: Test
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/setup-terraform
      - run: |
          mage -v config
          mage -v test
        env:
          TF_CREDENTIALS: ${{ secrets.TF_CREDENTIALS }}
