name: Workflow - On All Branches

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-go
        with:
          go-version: 1.17.3
      - uses: actions/cache@v2
        id: cache-vendor
        with:
          path: vendor/
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
      - run: |
          go mod vendor
        if: steps.cache-vendor.outputs.cache-hit != 'true'
      - uses: ./.github/actions/setup-terraform
      - run: |
          mage -v lint

  test:
    runs-on: ubuntu-20.04
    name: Test
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-go
        with:
          go-version: 1.17.3
      - uses: actions/cache@v2
        id: cache-vendor
        with:
          path: vendor/
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
      - run: |
          go mod vendor
        if: steps.cache-vendor.outputs.cache-hit != 'true'
      - uses: ./.github/actions/setup-terraform
      - run: |
          mage -v test
