name: Workflow - On Pull Requests To Main Branch

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-go
        with:
          go-version: 1.17.3
      - uses: ./.github/actions/setup-terraform
      - run: |
          mage -v config
          mage -v build live
        env:
          TF_CREDENTIALS: ${{ secrets.TF_CREDENTIALS }}

  release:
    runs-on: ubuntu-20.04
    name: Release
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-go
        with:
          go-version: 1.17.3
      - uses: ./.github/actions/setup-terraform
      - run: |
          mage -v config
          mage -v release live
        env:
          TF_CREDENTIALS: ${{ secrets.TF_CREDENTIALS }}
